version: "2"

run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errorlint
    - goconst
    - gocritic
    - misspell
    - nilerr
    - revive
    - unconvert
    - unparam

formatters:
  enable:
    - gofmt
